export let MockData = [
  {
    id: "c65d26dc-9e2d-465e-b252-708b4063af2e",
    personalDetails: {
      name: "Keshav",
      fatherName: null,
      address1: null,
      address2: null,
      city: null,
      state: null,
      pincode: null,
      nativeTown: null,
      mobileNumber: "9856472890",
      phoneNumber: null,
      creed: null,
      category: null,
      jain: true,
    },
    updateDocuments: {
      aadhaarNumber: "76573257823238",
      rationCard: "87268723538",
      bankAccount: "63287632823",
    },
    miscellaneous: {
      pathhala: null,
      religiousEducation: null,
    },
    monthlyExpenses: {},
    homeFurniture: {},
    dependentDetails: {
      dependentList: null,
      unemployedPerson: null,
      previousLoan: null,
      loanAmount: null,
    },
    medicalGrant: {},
    slillDetails: null,
    administrationDetails: {
      referredBy: null,
      address: null,
    },
    earningMembers: null,
  },
  {
    id: "c65d26dc-9e2d-465e-b252-708b4063af2e",
    personalDetails: {
      name: "Sumit",
      fatherName: null,
      address1: null,
      address2: null,
      city: null,
      state: null,
      pincode: null,
      nativeTown: null,
      mobileNumber: "9372383279",
      phoneNumber: null,
      creed: null,
      category: null,
      jain: null,
    },
    updateDocuments: {
      aadhaarNumber: "1289236823621",
      rationCard: "32986329863296",
      bankAccount: "6239632939621",
    },
    miscellaneous: {
      pathhala: null,
      religiousEducation: null,
    },
    monthlyExpenses: {},
    homeFurniture: {},
    dependentDetails: {
      dependentList: null,
      unemployedPerson: null,
      previousLoan: null,
      loanAmount: null,
    },
    medicalGrant: {},
    slillDetails: null,
    administrationDetails: {
      referredBy: null,
      address: null,
    },
    earningMembers: null,
  },
  {
    id: "c65d26dc-9e2d-465e-b252-708b4063af2e",
    personalDetails: {
      name: "Virender Kumar",
      fatherName: null,
      address1: null,
      address2: null,
      city: null,
      state: null,
      pincode: null,
      nativeTown: null,
      mobileNumber: "8383739739",
      phoneNumber: null,
      creed: null,
      category: null,
      jain: null,
    },
    updateDocuments: {
      aadhaarNumber: "1621612912621",
      rationCard: "290723973339",
      bankAccount: "83923869386932",
    },
    miscellaneous: {
      pathhala: null,
      religiousEducation: null,
    },
    monthlyExpenses: {},
    homeFurniture: {},
    dependentDetails: {
      dependentList: null,
      unemployedPerson: null,
      previousLoan: null,
      loanAmount: null,
    },
    medicalGrant: {},
    slillDetails: null,
    administrationDetails: {
      referredBy: null,
      address: null,
    },
    earningMembers: null,
  },
  {
    id: "c65d26dc-9e2d-465e-b252-708b4063af2e",
    personalDetails: {
      name: "Rahul Dave",
      fatherName: null,
      address1: null,
      address2: null,
      city: null,
      state: null,
      pincode: null,
      nativeTown: null,
      mobileNumber: "6686987392",
      phoneNumber: null,
      creed: null,
      category: null,
      jain: null,
    },
    updateDocuments: {
      aadhaarNumber: "76573257823238",
      rationCard: "87268723538",
      bankAccount: "63287632823",
    },
    miscellaneous: {
      pathhala: null,
      religiousEducation: null,
    },
    monthlyExpenses: {},
    homeFurniture: {},
    dependentDetails: {
      dependentList: null,
      unemployedPerson: null,
      previousLoan: null,
      loanAmount: null,
    },
    medicalGrant: {},
    slillDetails: null,
    administrationDetails: {
      referredBy: null,
      address: null,
    },
    earningMembers: null,
  },
  {
    id: "c65d26dc-9e2d-465e-b252-708b4063af2e",
    personalDetails: {
      name: "Sanjay",
      fatherName: null,
      address1: null,
      address2: null,
      city: null,
      state: null,
      pincode: null,
      nativeTown: null,
      mobileNumber: "9856472890",
      phoneNumber: null,
      creed: null,
      category: null,
      jain: null,
    },
    updateDocuments: {
      aadhaarNumber: "76573257823238",
      rationCard: "87268723538",
      bankAccount: "63287632823",
    },
    miscellaneous: {
      pathhala: null,
      religiousEducation: null,
    },
    monthlyExpenses: {},
    homeFurniture: {},
    dependentDetails: {
      dependentList: null,
      unemployedPerson: null,
      previousLoan: null,
      loanAmount: null,
    },
    medicalGrant: {},
    slillDetails: null,
    administrationDetails: {
      referredBy: null,
      address: null,
    },
    earningMembers: null,
  },
  {
    id: "c65d26dc-9e2d-465e-b252-708b4063af2e",
    personalDetails: {
      name: "Dinesh Karthik",
      fatherName: null,
      address1: null,
      address2: null,
      city: null,
      state: null,
      pincode: null,
      nativeTown: null,
      mobileNumber: "9372332792",
      phoneNumber: null,
      creed: null,
      category: null,
      jain: null,
    },
    updateDocuments: {
      aadhaarNumber: "1289236823621",
      rationCard: "32986329863296",
      bankAccount: "6239632939621",
    },
    miscellaneous: {
      pathhala: null,
      religiousEducation: null,
    },
    monthlyExpenses: {},
    homeFurniture: {},
    dependentDetails: {
      dependentList: null,
      unemployedPerson: null,
      previousLoan: null,
      loanAmount: null,
    },
    medicalGrant: {},
    slillDetails: null,
    administrationDetails: {
      referredBy: null,
      address: null,
    },
    earningMembers: null,
  },
  {
    id: "c65d26dc-9e2d-465e-b252-708b4063af2e",
    personalDetails: {
      name: "Sanjana",
      fatherName: null,
      address1: null,
      address2: null,
      city: null,
      state: null,
      pincode: null,
      nativeTown: null,
      mobileNumber: "8383397399",
      phoneNumber: null,
      creed: null,
      category: null,
      jain: null,
    },
    updateDocuments: {
      aadhaarNumber: "1621612912621",
      rationCard: "290723973339",
      bankAccount: "83923869386932",
    },
    miscellaneous: {
      pathhala: null,
      religiousEducation: null,
    },
    monthlyExpenses: {},
    homeFurniture: {},
    dependentDetails: {
      dependentList: null,
      unemployedPerson: null,
      previousLoan: null,
      loanAmount: null,
    },
    medicalGrant: {},
    slillDetails: null,
    administrationDetails: {
      referredBy: null,
      address: null,
    },
    earningMembers: null,
  },
  {
    id: "c65d26dc-9e2d-465e-b252-708b4063af2e",
    personalDetails: {
      name: "Jatin",
      fatherName: null,
      address1: null,
      address2: null,
      city: null,
      state: null,
      pincode: null,
      nativeTown: null,
      mobileNumber: "8668698732",
      phoneNumber: null,
      creed: null,
      category: null,
      jain: null,
    },
    updateDocuments: {
      aadhaarNumber: "76573257823238",
      rationCard: "87268723538",
      bankAccount: "63287632823",
    },
    miscellaneous: {
      pathhala: null,
      religiousEducation: null,
    },
    monthlyExpenses: {},
    homeFurniture: {},
    dependentDetails: {
      dependentList: null,
      unemployedPerson: null,
      previousLoan: null,
      loanAmount: null,
    },
    medicalGrant: {},
    slillDetails: null,
    administrationDetails: {
      referredBy: null,
      address: null,
    },
    earningMembers: null,
  },
];
